### ISSUE TITLE
@小猴机器人 哈罗，有没有kdd 2014 accepted paper list啊？

### ISSUE THREAD

**Issue by haoawesome** [memect/hao#138]

**Comment by licaoyuan123** [comment]
有没有kdd 2015 accepted paper list啊？

**Comment by haoawesome** [comment]
http://www.kdd.org/kdd2015/program.html 每天的schedule里有Accepted 
Papers by Session 算是一个list吧

**Comment by licaoyuan123** [comment]
http://dl.acm.org/citation.cfm?id=2783258#prox  找到了，谢谢你！
