### ISSUE TITLE
@付超群 不知道有没有中文发音相似度计算算法或者类库？比如北京 百斤 鼻颈 背景 如果可以顺道比较英文更好，比如peking，beking 感谢

### ISSUE THREAD

**Issue by haoawesome** [memect/hao#164]
私信

**Comment by bestFannie** [comment]
请问有找到比较“北京”和“Peking”发音相似性的方法吗？

**Comment by dongyuwei** [comment]
推荐一下 https://yomguithereal.github.io/talisman/phonetics/ 里面提供了16种语音相似性算法。
我的 [hallelujahIM](https://github.com/dongyuwei/hallelujahIM) 输入法使用了其中的 phonex 算法来实现英语语音模糊匹配功能。
