### ISSUE TITLE
呯呀么呯 有哪些好用的图像识别免费样本集呢？

### ISSUE THREAD

**Issue by haoawesome** [memect/hao#222]
我再问点问题哦。。做图像识别需要大量的训练样本对呗，那网上有多少现成的样本呢？我就知道Mnist，cifar10这样很经典的样本集，还有就是ImageNet了。。。有没有人总结过，有哪些好用的免费样本集呢？我在做智能交通方面的图像识别，一般去哪里找相关的样本集呢？

**Comment by matakk** [comment]
请问 哪里有公路上的视频监控视角的行人数据集呢？
类似 VOCdevkit 里面的数据集
